# Site settings
title: Las Cuatro Paredes
email: jgra86@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://Caquita-beep.github.io" # the base hostname & protocol for your site
twitter_username: Yet_another_ODE
github_username:  Caquita-beep

# Build settings
markdown: kramdown
